# Generated by Django 6.0.3 on 2026-03-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Open/Close Hand', 'Open/Close Hand'), ('Thumb-Index Pinch', 'Thumb-Index Pinch'), ('Finger spread', 'Finger spread'), ('Finger curl', 'Finger curl')], max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('reps_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
